"""Shared helpers for the Data Merge Engine page: saving uploads, and
exporting the persons table to CSV/Excel/PDF/SQL. Kept separate from the
page module itself so the export logic is easy to find and reuse.
"""
import csv
import io
import logging
import os
from datetime import datetime, timezone

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Table, TableStyle

logger = logging.getLogger(__name__)

UPLOAD_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                           "data", "uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)

PERSONS_COLUMNS = ["person_id", "full_name", "email", "phone", "city",
                    "source_systems", "skill_category", "created_at"]


def save_upload(conn, uploaded_file):
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%f")
    safe_name = uploaded_file.name.replace("/", "_")
    stored_path = os.path.join(UPLOAD_DIR, f"{ts}_{safe_name}")
    with open(stored_path, "wb") as f:
        f.write(uploaded_file.getbuffer())

    try:
        with open(stored_path, newline="") as f:
            row_count = max(sum(1 for _ in csv.reader(f)) - 1, 0)  # minus header
    except Exception:
        logger.warning("Could not count rows in uploaded file %s", stored_path, exc_info=True)
        row_count = None

    with conn.cursor() as cur:
        cur.execute(
            "INSERT INTO uploaded_files (original_filename, stored_path, "
            "row_count, status) VALUES (%s, %s, %s, 'pending')",
            (uploaded_file.name, stored_path, row_count),
        )
    conn.commit()


def fetch_people_df(conn):
    with conn.cursor() as cur:
        cur.execute(f"SELECT {', '.join(PERSONS_COLUMNS)} FROM persons ORDER BY person_id")
        rows = cur.fetchall()
    return pd.DataFrame(rows, columns=PERSONS_COLUMNS)


def to_csv_bytes(df):
    return df.to_csv(index=False).encode("utf-8")


def to_excel_bytes(df):
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="people")
        # Excel auto-detects all-digit columns (phone, person_id) as
        # numbers, which risks scientific notation / dropped leading
        # digits on longer values -- force phone to text explicitly.
        if "phone" in df.columns:
            ws = writer.sheets["people"]
            col_idx = list(df.columns).index("phone") + 1
            for row in range(2, len(df) + 2):
                ws.cell(row=row, column=col_idx).number_format = "@"
    return buf.getvalue()


def to_pdf_bytes(df):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(letter),
                             leftMargin=24, rightMargin=24, topMargin=24, bottomMargin=24)
    styles = getSampleStyleSheet()
    cell_style = styles["BodyText"]
    cell_style.fontSize = 7
    cell_style.leading = 9
    header_style = styles["BodyText"].clone("header")
    header_style.fontSize = 8
    header_style.textColor = colors.white

    data = [[Paragraph(str(c), header_style) for c in df.columns]]
    for _, row in df.iterrows():
        data.append([Paragraph("" if pd.isna(v) else str(v), cell_style) for v in row])

    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#142850")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f2f2")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    doc.build([table])
    return buf.getvalue()


def _sql_escape(value):
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def to_sql_bytes(df):
    lines = [
        "-- Generated by Nexora -- Data Merge Engine",
        f"-- {len(df)} rows from the persons table",
        "",
    ]
    cols = ", ".join(PERSONS_COLUMNS)
    for _, row in df.iterrows():
        values = ", ".join(_sql_escape(row[c]) for c in PERSONS_COLUMNS)
        lines.append(f"INSERT INTO persons ({cols}) VALUES ({values});")
    return ("\n".join(lines) + "\n").encode("utf-8")
